name: CI/CD Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 152.67.75.202 >> ~/.ssh/known_hosts

    - name: Deploy and restart bot
      run: |
        ssh -i ~/.ssh/id_ed25519 ubuntu@152.67.75.202 << 'EOF'
          cd /home/ubuntu/ShoppingOrganizerBot
          git pull origin master
          mvn clean install
          sudo systemctl restart shoppingbot
        EOF

    - name: Checking the bot launch
      run: |
        ssh -i ~/.ssh/id_ed25519 ubuntu@152.67.75.202 'sudo systemctl status shoppingbot --no-pager'